:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - [default, 10]
  - [critical, 30]

:scheduler:
  :enabled: true
  :schedule:
    process_submissions:
      every: "15sec"
      class: SubmissionManagement::Crons::ProcessAll
      queue: critical
      description: ""
    process_batch_statuses:
      every: "15sec"
      class: SubmissionManagement::Crons::CheckBatchStatuses
      queue: critical
      description: ""
